### ISSUE TITLE
Upgrade build dependency to v1.x

### ISSUE THREAD

**Issue by maxg203** [pyodide/matplotlib-pyodide#43]
We use `build==0.10.0` and there are breaking changes related to the `IsolatedEnvBuilder` class, which our entire test suite currently depends on. See their change log here:

https://pypa-build.readthedocs.io/en/latest/changelog.html#id2

**Comment by ryanking13** [comment]
What kind of build error do you see when you use `build>1.0.0`?

**Comment by maxg203** [comment]
It was unable to import `IsolatedEnvBuilder` as it was renamed in the upgrade. It looks like the internals are also changed quite heavily so I'm not certain it would be as simple as renaming the reference to it. This work would be to upgrade the package, fix the import error, make sure things work again and check for regressions. Apologies for the slow reply.

**Comment by ryanking13** [comment]
I see. Since `matplotlib-pyodide` is a simple pure python library, I guess we don't need to restrict the pypa/build version. Let me remove the constraint.
