### ISSUE TITLE
Publish release: new version 0.2.3 

### ISSUE THREAD

**Issue by agriyakhetarpal** [pyodide/matplotlib-pyodide#60]
[`v0.2.2...main`](https://github.com/pyodide/matplotlib-pyodide/compare/v0.2.2...main) shows that #52 did not make it to a release. Could we publish a release, @hoodmane and @ryanking13? I'd like to do a release so that I can use this in pyodide/pyodide#4510 and potentially revive that effort, as a part of the last rung towards NumPy v2 in Pyodide. I can additionally go ahead and clean up some parts of the repository (for example, we still test on [Pyodide 0.25.0](https://github.com/pyodide/matplotlib-pyodide/blob/18cd638fb0b70078c0e6bedc4a98331ac7652f33/.github/workflows/main.yml#L21)) and later, look into more of the open issues here where I can. Thanks!

**Comment by ryanking13** [comment]
> I can additionally go ahead and clean up some parts of the repository (for example, we still test on [Pyodide 0.25.0](https://github.com/pyodide/matplotlib-pyodide/blob/18cd638fb0b70078c0e6bedc4a98331ac7652f33/.github/workflows/main.yml#L21)) and later, look into more of the open issues here where I can. Thanks!

Sounds good to me!

**Comment by ryanking13** [comment]
After releasing 0.2.3. I think we could consider switching it to maintenance-only mode. Opened a proposal about it: #65

**Comment by agriyakhetarpal** [comment]
I've pushed a new 0.2.3 tag: https://github.com/pyodide/matplotlib-pyodide/releases/tag/v0.2.3 and a new release was created via https://github.com/pyodide/matplotlib-pyodide/actions/runs/12357340508/job/34485353235. I noticed that the attestations did not work because we didn't have trusted publishing enabled. I'll open a separate PR to update the publishing-related workflows in a moment, in a similar vein to pyodide/pyodide-build#33.

<hr> 

Link to release: https://pypi.org/project/matplotlib-pyodide/0.2.3/. 

We can resolve this issue for now. Thanks!
